stages:
  - test

playwright_test:
  stage: test
  image: mcr.microsoft.com/playwright:latest
  script:
    - apt-get update -qy
    - apt-get install -y --no-install-recommends libnss3 libatk-bridge2.0-0 libgtk-3-0
    - npm ci

    - npm run test-headless  

  only:
    - main  

  artifacts:
    paths:
    - playwright-report/
